### ISSUE TITLE
Docker update on Unraid 6.3.2 error

### ISSUE THREAD

**Issue by martindell** [tobbenb/docker-containers#11]
Docker: Tvheadend4-Stable-DVB-Tuners
Repository: https://github.com/tobbenb/docker-containers/tree/templates

Error: Pulling image: tobbenb/tvheadend:latest
TOTAL DATA PULLED: 0 B
Error: Error: image tobbenb/tvheadend:latest not found

**Comment by tobbenb** [comment]
I deleted it as I'm not updating it anymore. I have moved to linuxserver.io so use that version instead.
[https://github.com/linuxserver/docker-tvheadend](url)
Search for tvheadend in apps and choose the linuxserver one. You need to move the content of the .hts folder to the root of the appdata folder for the linuxserver container. You also need to configure xmltv if you used it before.
If you need more help, please use the unraid forum support thread.
