### ISSUE TITLE
Default login?

### ISSUE THREAD

**Issue by ghost** [tobbenb/docker-containers#8]
i installed your wonderful docker image
how can i login to the webgui ?

**Comment by tobbenb** [comment]
Which container?
Tvheadend is IP:9981
Oscam is IP:8888
Makemkv & mkvtoolnix is IP:8080 for webgui and IP:3389 for RDP.

**Comment by ghost** [comment]
tvheadend

**Comment by tobbenb** [comment]
I'm closing this since you have the solution.
